---
extends: default

rules:
  document-start: disable
  line-length: disable
  comments: disable
  indentation:
    spaces: consistent
    indent-sequences: consistent
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']

ignore: |
  dist/**
  node_modules/**
